# Module manifest for module 'PSEncryptTool'
# Generated by: lucidhominid
# Generated on: 3/19/2021
@{ 
    RootModule        = 'PSEncryptTool.psm1' 
    ModuleVersion     = '1.0' 
    GUID              = '41a8298d-2de7-4546-a13d-1b45337753bc' 
    Author            = 'lucidhominid' 
    CompanyName       = 'lucidhominid' 
    Copyright         = '(c) 2021 lucidhominid. All rights reserved.' 
    PowerShellVersion = '5.1.0.0' 
    FunctionsToExport = '*' 
    CmdletsToExport   = '*' 
    VariablesToExport = '*' 
    AliasesToExport   = '*' 
    PrivateData = @{    
        PSData = @{         
            # Tags = @()         
            # LicenseUri = ''         
            # ProjectUri = ''         
            # IconUri = ''         
            # ReleaseNotes = ''
        }
    }   
    # Description = '' 
    # CompatiblePSEditions = @() 
    # PowerShellHostName = '' 
    # PowerShellHostVersion = '' 
    # DotNetFrameworkVersion = '' 
    # CLRVersion = '' 
    # ProcessorArchitecture = '' 
    # RequiredModules = @() 
    # RequiredAssemblies = @() 
    # ScriptsToProcess = @() 
    # TypesToProcess = @() 
    # FormatsToProcess = @() /ModuleToProcess
    # NestedModules = @() 
    # DscResourcesToExport = @() 
    # ModuleList = @() 
    # FileList = @() 
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

